project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('User/', include('Users.url',namespace='User')),
    path('Dashboard/', include('Dashboard.url',namespace='Dashboard')),
    path('admin/', admin.site.urls),
    path('', include('webs.url',namespace='webs')),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/models.py
from django.db import models

# Create your models here.

webs/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from Users.models import *





# models.py

from django.db import models
from django.contrib.sessions.models import Session


class WEB(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    Employee_WEB = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='employee', blank=True, null=True)
    active = models.BooleanField(default=False)
    slug = models.CharField(max_length=50, unique=True, blank=True, null=True)
    FaviconIco= models.FileField(upload_to = "files/images/WEB/FaviconIco/%Y/%m/%d/",blank=True, null=True)
    logo = models.FileField(upload_to = "files/images/WEB/logo/%Y/%m/%d/",blank=True, null=True)
    keywords= models.CharField(max_length = 300,blank=True, null=True)
    pixal_id= models.CharField(max_length=500,blank=True, null=True)
    Title = models.CharField(max_length=100,blank=True, null=True)
    Title_logo = models.FileField(upload_to = "files/images/WEB/Title_logo/%Y/%m/%d/",blank=True, null=True)
    silderImage = models.FileField(upload_to = "files/images/WEB/silderImage/%Y/%m/%d/",blank=True, null=True)
    info = models.CharField(max_length = 300 ,blank=True, null=True)
    Description= models.CharField(max_length = 300 ,blank=True, null=True)
    PHONE = models.CharField(max_length = 300 ,blank=True, null=True)
    Whatsapp= models.CharField(max_length=500,blank=True, null=True)
    linkedinlinke= models.CharField(max_length=500,blank=True, null=True)
    snapchat= models.CharField(max_length=500,blank=True, null=True)
    instagramlinke= models.CharField(max_length=500,blank=True, null=True)
    Twitterlinke= models.CharField(max_length=500,blank=True, null=True)
    facebooklinke= models.CharField(max_length=500,blank=True, null=True)
    OpeningHours= models.CharField(max_length=500,blank=True, null=True)
    Address= models.CharField(max_length=500,blank=True, null=True)
    Map_Address= models.CharField(max_length=500,blank=True, null=True)
    views = models.IntegerField(default=0,blank=True, null=True)
    views_Categories = models.IntegerField(default=0,blank=True, null=True)
    views_checkout = models.IntegerField(default=0,blank=True, null=True)
    views_confirmation = models.IntegerField(default=0,blank=True, null=True)
    Click_booking= models.IntegerField(default=0,blank=True, null=True)
    Click_whatsapp= models.IntegerField(default=0,blank=True, null=True)
    Click_whatsapp_Categories= models.IntegerField(default=0,blank=True, null=True)

    def __str__(self):
         return self.slug

    def delete(self, *args, **kwargs):
        self.FaviconIco.delete()
        self.logo.delete()
        self.Title_logo.delete()
        self.silderImage.delete()

        super().delete(*args, **kwargs)



class Department(models.Model):
    web=models.ForeignKey(WEB,on_delete=models.CASCADE, related_name='department', blank=True, null=True)
    name = models.CharField(max_length=100)


class Questions(models.Model):
    web = models.ForeignKey(WEB, related_name='qestions', on_delete=models.CASCADE)
    question= models.CharField(max_length = 300 ,blank=True, null=True)
    answer = models.CharField(max_length=300,blank=True, null=True)
    def __str__(self):
         return self.question

#
class Image(models.Model):
   web=models.ForeignKey(WEB,on_delete=models.CASCADE, related_name='image', blank=True, null=True)
   image = models.FileField(upload_to = "files/images/WEB/Image/%Y/%m/%d/",blank=True, null=True)
   imagename = models.CharField(max_length = 300 ,blank=True, null=True)

   def __str__(self):
         return self.imagename

   def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args, **kwargs)


#
class Insurance(models.Model):
   web=models.ForeignKey(WEB,on_delete=models.CASCADE, related_name='insurance', blank=True, null=True)
   name = models.CharField(max_length = 300 ,blank=True, null=True)
   def __str__(self):
         return self.name
#
class Section(models.Model):

   web=models.ForeignKey(WEB,on_delete=models.CASCADE, related_name='section', blank=True, null=True)
   name = models.CharField(max_length = 300 ,blank=True, null=True)
   image = models.FileField(upload_to = "files/images/WEB/Section/%Y/%m/%d/",blank=True, null=True)


   def __str__(self):
         return self.name

#
class Doctors(models.Model):
   web=models.ForeignKey(WEB,on_delete=models.CASCADE, related_name='doctors', blank=True, null=True)
   Image = models.FileField(upload_to = "files/images/WEB/Doctors/%Y/%m/%d/",blank=True, null=True)
   Name = models.CharField(max_length = 300 ,blank=True, null=True)
   jobtitle= models.CharField(max_length = 300 ,blank=True, null=True)
#
   def delete(self, *args, **kwargs):
        self.Image.delete()
        super().delete(*args, **kwargs)
#



# __________________________________

class Categories(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    keywords = models.CharField(max_length=300, blank=True, null=True)
    Image = models.FileField(upload_to="files/images/WEB/Categories/%Y/%m/%d/", blank=True, null=True)
    Name = models.CharField(max_length=300, blank=True, null=True)
    web = models.ForeignKey(WEB, on_delete=models.CASCADE, related_name='categories', blank=True, null=True)
    views = models.IntegerField(default=0,blank=True, null=True)
    Click_whatsapp= models.IntegerField(default=0,blank=True, null=True)
    def __str__(self):
        return self.Name
    #
    def delete(self, *args, **kwargs):
        self.Image.delete()
        super().delete(*args, **kwargs)






class Service(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    keywords = models.CharField(max_length=300, blank=True, null=True)
    Image = models.FileField(upload_to="files/images/WEB/Service/%Y/%m/%d/", blank=True, null=True)
    Title = models.CharField(max_length=100)
    Description = models.CharField(max_length=500, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category_id=models.ForeignKey(Categories,on_delete=models.CASCADE, related_name='Services', blank=True, null=True)
    long_image = models.FileField(upload_to = "files/images/WEB/Service/long/%Y/%m/%d/",blank=True, null=True)
    views = models.IntegerField(default=0,blank=True, null=True)
    Click_booking= models.IntegerField(default=0,blank=True, null=True)
    Click_whatsapp= models.IntegerField(default=0,blank=True, null=True)
    #
    # def __str__(self):
    #     return self.Title

    def delete(self, *args, **kwargs):
        self.Image.delete()
        self.long_image.delete()
        super().delete(*args, **kwargs)



#
# class ArticleSeries(models.Model):
#     def image_upload_to(self, instance=None):
#         if instance:
#             return os.path.join("ArticleSeries", slugify(self.slug), instance)
#         return None
#
#     title = models.CharField(max_length=200)
#     subtitle = models.CharField(max_length=200, default="", blank=True)
#     slug = models.SlugField("Series slug", null=False, blank=False, unique=True)
#     published = models.DateTimeField("Date published", default=timezone.now)
#     author = models.ForeignKey(get_user_model(), default=1, on_delete=models.SET_DEFAULT)
#     image = models.ImageField(default='default/no_image.jpg', upload_to=image_upload_to ,max_length=255)
#
#
#








class CartItem(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    web = models.ForeignKey(WEB, on_delete=models.CASCADE,  blank=True, null=True)






class Appointment(models.Model):

    Undefined = "كيف عرفتنا"
    insurance = 'تأمين'
    Friend = 'صديق '
    family = 'أسرة'
    neighbors = 'الجيران'
    Google = 'جوجل '
    Whatsapp = 'واتساب'
    snapchat = 'سناب'
    Instagram = 'انستقرام'
    Twitter = 'تويتر'
    Facebook = 'فيس بوك '
    ticktock = 'تيك توك'
    YouTube = 'يوتيوب '
    Email = 'البريد الإلكتروني'
    Site = 'موقع'
    other = 'آخر'

    CHOICES_knew = (
        (Undefined, "كيف عرفتنا"),
        (insurance, 'تأمين'),
        (Friend, 'صديق '),
        (family, 'أسرة'),
        (neighbors, 'الجيران'),
        (Google, 'جوجل '),
        (Whatsapp, 'واتساب'),
        (snapchat, 'سناب'),
        (Instagram, 'انستقرام'),
        (Twitter, 'تويتر'),
        (Facebook, 'فيس بوك '),
        (ticktock, 'تيك توك'),
        (YouTube, 'يوتيوب '),
        (Email, 'البريد الإلكتروني'),
        (Site, ' موقع الإلكتروني'),
        (other, 'آخر'),
    )

    waiting = 'انتظار'
    Inquiries="الاستفسار"
    notanswering= 'عدم الرد'
    cancel ='إلغاءحجزه'
    confirmed="حجز مؤكد"
    Visit =  'حضر'

    STATUS_CHOICES = (('waiting','انتظار'),('inquiries', 'الاستفسار'),('cancel', 'إلغاءحجزه'),('notanswering', 'عدم الرد'),('confirmed', 'حجز مؤكد'),    ('visit', 'حضر'),)
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    service=models.ManyToManyField(Service,blank=True)
    web = models.ForeignKey(WEB, on_delete=models.CASCADE, blank=True, null=True)
    knew_from = models.CharField(max_length=50, choices=CHOICES_knew, blank=True, null=True)
    status_appointment =models.CharField(max_length=30, choices=STATUS_CHOICES , default=waiting)
    note = models.CharField(max_length=500, blank=True, null=True)

Dashboard/forms.py
from django import forms
from webs.models import *

class WebForm(forms.ModelForm):
    class Meta:
        model = WEB
        fields = "__all__"
        exclude = ['Employee_WEB' ,'views','views_Categories','views_checkout','views_checkout','views_confirmation','Click_booking','Click_whatsapp','Click_whatsapp_Categories']


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctors
        fields = ['Name', 'jobtitle', 'Image']


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ['name','image']



class InsuranceForm(forms.ModelForm):
    class Meta:
        model = Insurance
        fields = ['name']


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'imagename']


class QuestionsForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = ['question', 'answer']
        widgets = {
        'question': forms.Textarea(attrs={'rows': 5}),
         'answer': forms.Textarea(attrs={'rows': 5}),
         }





class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']




class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = "__all__"
        exclude =['views','web' ]


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('active', 'Title', 'Description', 'Image', 'price',  'keywords','long_image')
        exclude =['views','Click_booking','Click_whatsapp']
        labels = {
            'active': 'Active',
            'Title': 'My Field Label',
            'Image': 'Image',
            'price': 'Price',
            'long_image':'Image',
            # 'category_id': 'Category ID',
        }
        widgets = {
            'Description': forms.Textarea(attrs={'rows': 5}),
            'keywords': forms.TextInput(attrs={'placeholder': 'e.g. keyword1, keyword2, keyword3','rows': 5}),
        }




class upServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('active', 'Title', 'Description', 'Image', 'price',  'keywords','category_id','long_image')
        exclude = ['views','Click_booking','Click_whatsapp']
        labels = {
            'active': 'Active',
            'Title': 'My Field Label',
            'Image': 'Image',
            'price': 'Price',
            'long_image':'Image',
            # 'category_id': 'Category ID',
        }
        widgets = {
            'Description': forms.Textarea(attrs={'rows': 5}),
            'keywords': forms.TextInput(attrs={'placeholder': 'e.g. keyword1, keyword2, keyword3'}),
        }

templates/booking_confirmation.html
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','{{web.pixal_id}}');</script>
<!-- End Google Tag Manager -->



<style media="screen">
  /* Style for the confirmation message */
.confirmation-message {
  margin: 50px auto;
  max-width: 600px;
  padding: 20px;
  text-align: center;
  border: 2px solid #ccc;
  border-radius: 10px;
}

/* Style for the booking ID */
.booking-id {
  font-size: 20px;
  font-weight: bold;
  margin-bottom: 20px;
}

/* Style for the back and view buttons */
.back-button,
.view-button {
  display: inline-block;
  padding: 10px 20px;
  background-color: #d1c091;
  color: #fff;
  text-decoration: none;
  border-radius: 5px;
  margin-top: 20px;
}

/* Style for the back button */
.back-button {
  margin-right: 10px;
}

/* Media queries for responsive design */
@media (max-width: 768px) {
  .confirmation-message {
    margin: 20px auto;
    padding: 10px;
  }

  .back-button,
  .view-button {
    display: block;
    width: 100%;
    margin-top: 10px;
  }
}
</style>







 <!-- Google Tag Manager (noscript) -->
 <noscript><iframe src="https://www.googletagmanager.com/ns.html?id={{web.pixal_id}}"
 height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
 <!-- End Google Tag Manager (noscript) -->





<!-- Confirmation message -->
<div class="confirmation-message">
  <h2>
  تم تأكيد حجزك!

 </h2>

  <p>
 شكرًا لاستخدام خدماتنا
   </p>

  <!-- Back and view buttons -->
  <a href="{% url 'webs:web' web %}" class="back-button">  عودة إلى الصفحة الرئيسية</a>
  <a href="{% url 'webs:categories_services' web  %}" class="view-button"> عرض المزيد من الفئات والخدمات</a>
</div>

templates/categories.html


{% extends "BaseGeneric.html" %}
{% load static %}
<title>{{web.slug}}  | {{category.Name}}  </title>
<meta name="keywords" content="{{ category.keywords }} " />
{% block content %}




   <!-- Google Tag Manager -->
   <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
   new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
   j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
   'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
 })(window,document,'script','dataLayer','{{web.pixal_id}}');</script>
   <!-- End Google Tag Manager -->














 <div class="topnav" id="myTopnav">
   {% if web.logo %}
    <a href="{% url 'webs:web' web.slug %}" class="active"><div class="div-logo" >
   <img src="{{web.logo.url}}" class="logo-img" alt="{{web}}"> </div> </a>{% endif %}
    <a href="{% url 'webs:web' web.slug %}">الصفحه الرئيسيه</a>
    <a href="{% url 'webs:categories_services'  web.slug   %}">جميع العروض  </a>


    {% for category in categories_nav %}

    <a href="{% url 'webs:categories' web.slug category.id %}">   {{category.Name}}      </a>
  {% endfor %}



    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
      <samp class="icon-span">
      <i class="fa fa-bars"></i>    </samp>
    </a>
  </div>
</header>




<style>
@import url('https://fonts.googleapis.com/css2?family=Cairo:slnt,wght@0,500;0,700;2,400&family=Koulen&family=Staatliches&display=swap');


#myImg {
  border-radius: 5px;
  cursor: pointer;
  transition: 0.3s;
}

#myImg:hover {opacity: 0.7;}




</style>


<section style="  height: auto;width:100%; margin: auto; margin-top: 15px; margin-bottom: 15px;">


     <!-- Google Tag Manager (noscript) -->
     <noscript><iframe src="https://www.googletagmanager.com/ns.html?id={{web.pixal_id}}"
     height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
     <!-- End Google Tag Manager (noscript) -->







<div style="width: 99%; margin: auto;">

<div style="width: 100%; margin: auto;">{% if category.Image %}
<img   src="{{category.Image.url}}" alt=" {{category.Name}} " style="width:100%;
box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 1px 3px 1px;">{% endif %}

</div>



<style type="text/css">


.section--title{
margin-right: 15px;
 text-align: center;

}
.divider {
  width: 150px;
  height: 5px;
  background-color: #d1c091;
  margin: auto;
  margin-top: 10px;
  margin-bottom: 10px;
  border-radius: 8px;
  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.3);
}

</style>





<div class="section-header ">
<h2 class="section--title"><span>{{category.Name}}</span></h2>

<hr class="divider">

</div>

<style>











.Container{

    /* background-color: lightgreen; */
      width: 99%;
    display: flex;
    flex-wrap: wrap;
    flex-direction: row;
    justify-content: center;
    align-content: flex-start;
    margin: auto;
    min-height: 30em;
    padding: 3em 1em 1em 1em;
    box-sizing: border-box;
}

/* Card Styling */
.card-div{    border: 1px solid #ccc;
    width: 20em;
    min-height: 20em;
    display: flex;
    flex-direction: column;
    justify-items: center;
    align-items: center;
    background-color: var(--card-main-color);
    margin: 0.6em;
    box-sizing: border-box;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    transition: transform 0.2s ease-in-out;
     border-radius: 8px ;
}

/* ======== General styling of all cards and heart divs ========== */
.img-div{
    width: 100%;
    height: 8em;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    padding-top: 1rem;
    z-index: 1;
    border-radius: 0 0 10px 10px;
}

.img-div img{
    transform-origin: bottom;
    transform: translateY(7.5%);
    transition: transform 0.3s ease-in-out
}



/* God of war image and heart-background*/
.gow-img-div{
    background-color: var(--card-1-secondary-color);
}

.gow-img-div img{
    width: 100%;
    border-radius: 8px 8px  0px  0px ;

    /* background-color: whitesmoke; */
}



/* ======== text Container Styling general ======== */

.text-container{
    width: 100%;
    display: flex;
    flex-direction: column;
    /* background-color: yellow; */
    padding: 0 1.5em;

    padding-bottom: 1em;
    box-sizing: border-box;
}

.text-container .item-name,
.text-container .date{
    margin: 0.25em 0;
    text-align: center;
}

.text-container .item-name{
    font-size: 1em;
    font-weight: var(--title-font-weight);
    color: var(--heading-color);
}

.text-container .date{
    font-size: 0.9em;
    font-weight: var(--date-font-weight);
    color: var(--date-text-color);
}

/* === Pricing and cart div  ===== */
.pricing-and-cart{
    /* background-color: wheat; */
    width: 100%;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    margin: 0.25em 0 1em 0;
}
.pricing{
    display: flex;
    flex-direction: column;
    text-align: right;
}


.current-price{
    color: var(--current-price-text-color);
    font-size: 1.3rem;
    font-weight: var(--pricing-font-weight);
    /* background-color: yellow; */
    margin: 0;

  color: #d1c091;;
    font-size: 22px;
    font-weight: 400;
    margin-bottom: .5rem;

}

.pricing-and-cart{
    width: 100%;
}

.fa-shopping-cart{
    font-size: 1rem;
    top: 0;
    color: #d1c091;
    padding:  3px ;
    color:#fff;
}
.add-to-cart{
  background-color:  #d1c091; /* orange color */
  border: none;
  outline: none;
  cursor: pointer;
  padding:  0px 5px  0px 5px   ;
  transition: 0.3s;
  font-size: 8px;
  border: 1px solid #ccc;
  border-radius: 50px;
  color: #fff;

}

/* ====== Hover effects ======= */
.card-div:hover .img-div img{
    transform: translateY(7.5%) scale(1.2);
}

.card-div:hover{
    transform: translate(0, -10px);
}


a {
  color: #d1c091;/* Set link color */
  text-decoration: none; /* Remove underline */
  font-weight: bold; /* Set font weight */
}

a:hover {

  /* text-decoration: underline; /* Add underline on hover */ */
}
.fa-shopping-cart:hover {

}

.add-to-cart:hover {
  transform: translateY(10%);
}
</style>


 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">





    <div class="Container">







      {% for service in category.Services.all %}
          <div class="card card-div">
  <a href="{% url 'webs:service' web.slug category.id service.id %}">
                  <div class="gow-img-div">
                      {% if service.Image %}
                          <img src="{{ service.Image.url }}" alt="{{ service.Title }}">
                      {% endif %}
                  </div>
              </a>
              <div class="text-container">
                  <a href="{% url 'webs:service' web.slug category.id service.id %}">
                      <h2 class="item-name">{{ service.Title }}</h2>
                  </a>
                  <div class="pricing-and-cart">
                      <div class="pricing">
                          <p class="current-price">{{ service.price }} ر.س</p>
                      </div>
                      <button class="add-to-cart" data-id="{{ service.id }}">
                      إضافة للسلة    <i class="fas fa-shopping-cart"></i>
                      </button>
                  </div>
              </div>
          </div>
      {% endfor %}












   </div>



</div>







</section>
<a class="button-card" href="{% url 'webs:cart_and_checkout' web.slug  %}">
<button class="notification-button">
<img src="{% static 'images/card.png' %}" alt="Image Description" class="notification-icon">
  {% if cart_item_count %}
<span class="notification-number"><span id="cart-count">

    {{ cart_item_count }}
  {% else %}
    <!-- 0 -->
  {% endif %}
</span>
</button>
</a>


<div class="floating_btn"id="whatsapp-button"> <a target="_blank" href="https://wa.me/{{web.Whatsapp}}  ">
        <div class="contact_icon"> <i class="fab fa-whatsapp my-float"></i> </div>
    </a> </div>



  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      $('#whatsapp-button').click(function() {
        $.ajax({

          url: '{% url "webs:increment_click_category_whatsapp" category_id=category.id %}',
          method: 'POST',
          data: {
            'csrfmiddlewaretoken': '{{ csrf_token }}',
          },
          success: function(response) {
            // Update the click count on the page
            $('#click-whatsapp-count').text(response.click_whatsapp);
          },
        });
      });
    });
  </script>


























{% endblock %}

templates/create_question.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #fff;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color:  #fff;
}

/* Set a style for all buttons */
.buttonform {
  background-color: #7e91dc;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

.buttonform:hover {
  opacity: 0.8;
}



</style>



<br><br><br>



<br><br>
<h2 style="color: #695CFE; text-align:center;"> {{title}}     </h2><br>
  <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}


    <div style="width: 99%; margin: auto;">






    <h2 style="color: #5a5a5a;
        font-size: 24px;
      <br>      <br>
        margin-bottom: 1rem;"> السؤال</h2>

{{ form.question  }}
      <br>      <br>

      <h2 style="color: #5a5a5a;
          font-size: 24px;
        <br>      <br>
          margin-bottom: 1rem;">  الاجابة</h2>

  {{ form.answer  }}

    <div>





        <br>

        <style media="screen">
          .btn_submit {
         background-color: var(--primary-color);
          color: white;
          padding: 10px 20px;
          border: none;
          border-radius: 5px;
          cursor: pointer;
          width: 100%;
        }
        </style>

          <button class="btn_submit" type="submit">Save</button>
            <br>
            <br>
            <br>
            <br>

        </form>

{% endblock %}

templates/create_web.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create Web Object</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
{% endblock %}

templates/edit_web.html
{% extends "base.html" %}








<style>

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #fff;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color:  #fff;
}

/* Set a style for all buttons */
.buttonform {
  background-color: #071c4d;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

.buttonform:hover {
  opacity: 0.8;
}



</style>










{% block content %}
  <h1>Edit web instance '{{ web.slug }}'</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="slug">Slug:</label>
      <input type="text" id="slug" name="slug" class="form-control" value="{{ web.slug }}" required>
    </div>
    <div class="form-group form-check">
      <input type="checkbox" id="active" name="active" class="form-check-input" {% if web.active %}checked{% endif %}>
      <label for="active" class="form-check-label">Active</label>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}